name = "bonbast-telegram-worker"
main = "src/index.ts"
compatibility_date = "2025-12-21"

[[kv_namespaces]]
binding = "BOT_KV"
id = "6a4eacff88d440f1b19230176395f533"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
